### ISSUE TITLE
Django JSON API view

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/pydantic-django#10]
Either a re-usable CBV or perhaps just some documentation would be good for how to create a basic JSON API view using the model schemas.

**Comment by vitalik** [comment]
Hi Jordan,

Looks like you working on a feature that I currently researching for a project **django-ninja**

https://github.com/vitalik/django-ninja

Specifically for now I'm just trying to develop usable/nice API for conecting Pydantic model and Django model

https://django-ninja.rest-framework.com/proposals/models/

----

I like your concept...
but I see particcular problem in adding too much methods to model namespace like:

```
user_schema = UserSchema.from_django(user)

user_schema = UserSchema.get(id=user.id)

UserSchema.create(...)

```

---

What I think the best is having some single attribute to access ORM:

```

UserSchema.objects --> will map to User.objects

so now you should be able to do

UserSchema.objects.get(...

UserSchema.objects.filter(...).first()


```

**Comment by jordaneremieff** [comment]
@vitalik I prefer that approach (single attribute access) and used it initially, but there is a difficult problem of chaining additional filter methods and accomodating custom manager methods so I opted to instead provide only basic queryset access with the intention that more complex queries would be performed using just Django ORM first then loaded into the model. I haven’t had a lot of time to look at this lately, but that is something I’ll probably revisit when I look into this next.

**Comment by jordaneremieff** [comment]
I think for now I'll leave it up to users to integrate the models with their endpoint views.
