### ISSUE TITLE
Do you accept PRs?

### ISSUE THREAD

**Issue by JulianFeinauer** [jordaneremieff/pydantic-django#13]
Hey,
this project is awesome and I would consider contributing a bit. Do you generally accept PRs?

Best!
Julian

**Comment by jordaneremieff** [comment]
Hi @JulianFeinauer.

I haven't had a lot of time to work on this recently, but I'd be happy to look at any PRs. However, this project is still in an experimental state, so I can't guarantee that work done in PRs will remain before the APIs and functionality are more finalised and supported.

Do you have any specific contributions in mind?

**Comment by JulianFeinauer** [comment]
Hey Jordan,

I worked a bit with FastAPI and Tortoise ORM and I really liked how Tortoise bridges the Gap to Pydantic / FastAPI. But since I want to use my Django Models your project comes into play. So nothing very special.. just playing around in this area, generally.

Julian

Von: Jordan Eremieff <notifications@github.com>
Antworten an: jordaneremieff/pydantic-django <reply@reply.github.com>
Datum: Mittwoch, 25. November 2020 um 13:36
An: jordaneremieff/pydantic-django <pydantic-django@noreply.github.com>
Cc: Julian Feinauer <j.feinauer@pragmaticminds.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jordaneremieff/pydantic-django] Do you accept PRs? (#13)


Hi @JulianFeinauer<https://github.com/JulianFeinauer>.

I haven't had a lot of time to work on this recently, but I'd be happy to look at any PRs. However, this project is still in an experimental state, so I can't guarantee that work done in PRs will remain before the APIs and functionality are more finalised and supported.

Do you have any specific contributions in mind?

**Comment by jordaneremieff** [comment]
@JulianFeinauer ah, cool. I'm not sure when I'm going to come back to this next, but I'll curate the issues tracker at some point and see if I can work out a general direction for things. If you have any ideas yourself, feel free to open an issue or comment on an existing one, and we can go from there.

**Comment by jordaneremieff** [comment]
@JulianFeinauer I've cleaned up the issue tracker a bit with the things I'm considering atm. Closing this issue now, but feel free to follow-up in the other issues or create your own with any ideas you might have.
